version: '3'

# networks: 
#   backend:
#     driver: bridge

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    network_mode: host      

  redis:
    image: redis
    restart: always
    ports: 
      - 6379:6379
    network_mode: host

  estore:
    image: 'estore'
    ports: 
      - 6000:7000
    network_mode: host

  



    