version: '3'

networks: 
  backend:
    driver: bridge

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - backend
    environment: 
      - bind-address=0.0.0.0

  redis:
    image: redis
    restart: always
    ports: 
      - 6379:6379
    networks:
      - backend

  estore:
    image: 'estore'
    ports: 
      - 6000:7000
    networks:
      - backend
    environment: 
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis


  



    